### ISSUE TITLE
Pyrax install downgrades python-novaclient

### ISSUE THREAD

**Issue by ChineduUzoka** [pycontribs/pyrax#600]
It appears that pyrax is incompatible with python-novaclient==3.2.0.  Python-novaclient is downgraded to version 2.27.0
This breaks apikey authentication with rackspace since that downgraded version of python-novaclient cannot authenticate correctly since it does not use APIKEY - 
This worked previously but im unsure what version of pyrax worked

**Comment by cardoe** [comment]
Likely the same as #616, which has more info so I'll close this in favor of that.
